// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertToWav(arg1, arg2) {
  return window['go']['main']['App']['ConvertToWav'](arg1, arg2);
}

export function GetModelInfo() {
  return window['go']['main']['App']['GetModelInfo']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadModel(arg1) {
  return window['go']['main']['App']['LoadModel'](arg1);
}

export function SaveAndTranscribeRecording(arg1) {
  return window['go']['main']['App']['SaveAndTranscribeRecording'](arg1);
}

export function TranscribeAudioData(arg1) {
  return window['go']['main']['App']['TranscribeAudioData'](arg1);
}

export function TranscribeFile(arg1) {
  return window['go']['main']['App']['TranscribeFile'](arg1);
}
