// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertToWav(arg1:string,arg2:string):Promise<void>;

export function GetModelInfo():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function LoadModel(arg1:string):Promise<void>;

export function SaveAndTranscribeRecording(arg1:Array<number>):Promise<string>;

export function TranscribeAudioData(arg1:Array<number>):Promise<string>;

export function TranscribeFile(arg1:string):Promise<string>;
